### ISSUE TITLE
import keras.backend.tensorflow_backend as tb Error "No module named tensorflow_backend"

### ISSUE THREAD

**Issue by aziz06193** [DeepNeuralAI/RL-DeepQLearning-Trading#24]
I have a code and I want to run the code but it shows an error as stated in Title.
I have tried other ways too as I noticed on github like,

1 : from tensorflow.keras.backend.tensorflow_backend import tensorflow_backend as tb

The actual code written in file is 

import keras.backend.tensorflow_backend as tb
tb._SYMBOLIC_SCOPE.value = True

KIndly let me know if anyone knows the solution to this problem,

**Comment by DeepNeuralAI** [comment]
Hi, 
This is an outdated version of TF. Either downgrade your TF to have the code work, or use an updated TF but you will have to change the code. Most likely you won't need the top lines you mentioned.
